### ISSUE TITLE
OAuth1 (maybe2) to support multiArgs on promisifyAll() call.

### ISSUE THREAD

**Issue by olegzd** [omouse/node-oauth-libre#10]
Hey Rudolf, in the patch file I edited the Promise.promisifyAll() to include  { multiArgs: true } as an argument. Bluebird's promises, unless it includes the above condition, does not support multiple arguments in a callback. OAuth.getOAuthRequestToken(arg1,arg2,arg3...) would only return arg1. 

I edited the promisifyAll() call to include that flag, do you see any problems* arising from it?

(related to #4 )

**Comment by omouse** [comment]
awesome thanks that's really helpful, I don't see an issue from this and I reviewed your patch @olegzd which I'll merge in this weekend, should be getting promises support fairly soon, this really helps move it along.

**Comment by omouse** [comment]
@olegzd merged the patch just now, thanks :smile:
