### ISSUE TITLE
State parameter handling

### ISSUE THREAD

**Issue by XVincentX** [omouse/node-oauth-libre#15]
Hello!
It looks like this library does not handle the `state` parameter. It would be great as it would reduce surface attacks via CSRF!

**Comment by omouse** [comment]
hi @XVincentX thanks for reporting this issue! I'll look into it for the 0.9.16 release. If it's urgent I may bump it up into 0.9.15 but this release is focused mainly on support for promises.

**Comment by XVincentX** [comment]
I am not in haste as I am handling that thing by myself, but I would love to get a notification when this gets implemented.

**Comment by caco0516** [comment]
@omouse I could take this one ir you want... Igual think this is a risky bug...

**Comment by omouse** [comment]
@caco0516 sounds good, this is for 0.9.16

**Comment by caco0516** [comment]
@XVincentX I'm not sure if this module should manage state for state parameter feature because this module main function is to serve as a "API call interface" , I mean with this library you can have all OAuth specification working ,and "state" is recommended but is not part of spec itself. 

For example I used node-oauth-libre with this [passport strategy](https://github.com/caco0516/passport-oauth2-libre/blob/master/lib/strategy.js#L123 ) . If you can see this passport strategy implements state parameter logic and just call node-oauth-libre methods like this: 
```javascript
exports.OAuth2.prototype.getOAuthAccessToken= function(code, params, callback) {
  var params= params || {};
  params['client_id'] = this._clientId;
  params['client_secret'] = this._clientSecret;
  var codeParam = (params.grant_type === 'refresh_token') ? 'refresh_token' : 'code';
  params[codeParam]= code;

  var post_data= querystring.stringify( params );
  
  var post_headers= {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Authorization': this._getAuthorizationHeader()
  };

  this._request("POST", this._getAccessTokenUrl(), post_headers, post_data, null, function(error, data, response) {
    if( error )  callback(error);
    else {
      var results;
      try {
        // As of http://tools.ietf.org/html/draft-ietf-oauth-v2-07
        // responses should be in JSON
        results= JSON.parse( data );
      }
      catch(e) {
        // .... However both Facebook + Github currently use rev05 of the spec
        // and neither seem to specify a content-type correctly in their response headers :(
        // clients of these services will suffer a *minor* performance cost of the exception
        // being thrown
        results= querystring.parse( data );
      }
      var access_token= results["access_token"];
      var refresh_token= results["refresh_token"];
      delete results["refresh_token"];
      callback(null, access_token, refresh_token, results); // callback results =-=
    }
  });
}
```

**params** argument let us to send state parameter from outside module. So we don't really need to implement this as part of module's core functionality. This is just an example of how you can add security to node-oauth-libre without modify core functions. 

What do you think @omouse . And I'm sorry for this but I was thinking about this I for me this is a better solution.

**Comment by omouse** [comment]
@caco0516 your approach makes sense, but [after reading through how the CSRF attack works](http://stackoverflow.com/questions/11071482/oauth2-0-server-stack-how-to-use-state-to-prevent-csrf-for-draft2-0-v20/23640462#23640462) it would seem like something that can be handled by node-oauth-libre, just make it another option to flip on "csrfStateProtected" and then look for "state" in the oauth access token method and store it.

There are only two questions in my mind on this:

1. does it increase complexity of the code too much?
1. does it break backwards compatibility?

**Comment by XVincentX** [comment]
Hey,
thanks a lot for considering this.
Obviously I do not want to force you guys to implement something you do not feel it's part of the library.

As of today I'm checking this thing manually wherever is needed - and I'm totally fine with that.
I just thought it would be a so common use case that it was worth including into.

**Comment by caco0516** [comment]
@omouse Ok I think this won't increase complexity ... My question is where we can store state ? We should use session just like [passport-oauth](https://github.com/caco0516/passport-oauth2-libre/blob/master/lib/strategy.js#L123) or maybe we can just expose simple methods to let's oauth-libre users implement their own store method , like a "plugin" system.

**Comment by omouse** [comment]
@caco0516 yeah I think having hooks when handling requests in the [_request method](https://github.com/omouse/node-oauth-libre/blob/master/lib/oauth2.js#L183) would be a good idea. Maybe using an event emitter?

    oauth2.on('request:before', setupCsrfStateProtection);
    oauth2.on('request:after', storeCsrfStateProtection);
    oauth2.get(whatever, function() {
    });

and with promises:

    oauth2promise.on('request:before', setupCsrfStateProtection);
    oauth2promise.on('request:after', storeCsrfStateProtection);
    oauth2promise.get(whatever).then(function() {
    });

I feel like we should dig through [the issues on the other repo](https://github.com/ciaranj/node-oauth/issues) to see what else would fit into a plugin architecture like this.

**Comment by caco0516** [comment]
@omouse Ok I like hooks idea. We could take this with that solution. I agree

**Comment by omouse** [comment]
ok cool, let's do that and then have an example in the readme that shows how to use it for storing state parameter so anyone who needs it can use it

**Comment by caco0516** [comment]
@omouse I would like to use node.js native event api [Events](https://nodejs.org/api/events.html#events_events). Is this ok for you ?

**Comment by omouse** [comment]
@caco0516 yep, for sure, I was reading over the docs for it on Friday heh https://nodejs.org/api/events.html#events_emitter_emit_eventname_args

**Comment by caco0516** [comment]
Great @omouse I will start working on it today. Wait for my PR ... 👍

**Comment by caco0516** [comment]
I will use [Utilities](https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor) library for backward compatibility. We should use extends form ES6 for next versions maybe 1.0.

**Comment by caco0516** [comment]
@omouse  I just made some changes please review PR #26 . Regards
