### ISSUE TITLE
Let's integrate this project to Travis CI

### ISSUE THREAD

**Issue by caco0516** [omouse/node-oauth-libre#20]
Hi @omouse , I wanna ask you for permission to submit this project to [TravisCI](https://travis-ci.org/), I could create a fork of this but the idea is to not fragment NPM libraries more and more. So if you like I could do the integration with CI platform. Let me know what do you think about this.

**Comment by omouse** [comment]
sounds like a great idea, I think I have another repo or two that are already in travis

**Comment by caco0516** [comment]
Great !!! 😄  . Will be waiting for this.

**Comment by omouse** [comment]
added a .travis.yml and here's a build: https://travis-ci.org/omouse/node-oauth-libre

didn't seem to work in these versions of node:

- 4.4
- 4.3
- 0.12
- 0.10

I'd like to support those if possible because I know that Amazon Lambda supports only 0.10.x or 4.3.x of Node.

**Comment by omouse** [comment]
closing this since travis does work, only enabled node 5.x and latest :+1:
